version: "3"
networks:
  default:
    external:
      name: traveler-dev
services:
  ldap-service:
    image: osixia/openldap:1.2.1
    command: --copy-service
    volumes:
      - ./seed:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - 389:389
  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    restart: unless-stopped
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-service
    depends_on:
      - ldap-service

